### ISSUE TITLE
Auto Connect not working via API (Cura Otcoprint Plugin)

### ISSUE THREAD

**Issue by Wob76** [jneilliii/OctoPrint-Domoticz#14]
Running Cura 4.5 and the Connect to OctoPrint 3.5.12, Octoprint 1.4.0, OctoPrint-Domoticz 0.1.1

This combination is working to power the printer up, but it doesn't initiate the auto connect after the power up. I have the Domoticz plugin configured to "Auto Connect" and GCODE on Delay, I have also tried adjusting the delays without change. The plugin does work as expected when using the Octoprint plugin Power Icon, or inserted start GCODE.

I opened an issue in the Cura Plugin and author reported that it appear this plugin does not issue a AutoConnect when using the API, could this be looked at? 
https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/164#issuecomment-604291797

Thanks,
Beau

**Comment by jneilliii** [comment]
@fieldsOfView is correct. The current implementation of the plugin handles the connection on the JavaScript/Web Interface side and not the python/server side. I'll need to make these adjustments the way I have in my other power plugins to resolve this.

**Comment by Wob76** [comment]
That would be great, it's not a major issue, I just have to open otcoprint and connect, but the updates with Cura are making the integration much nicer, this would mean I need very little interaction within octoprint to start a print.

**Comment by jneilliii** [comment]
Hey @Wob76, I just pushed an update to the 0.1.2 branch for testing. Use the URL below in Plugin Manager to install and verify for me prior to official release. After install please make sure to force a refresh of the browser is not prompted to Reload after installing/restarting.

https://github.com/jneilliii/OctoPrint-Domoticz/archive/0.1.2.zip

**Comment by Wob76** [comment]
Great, I'll give it a spin

**Comment by Wob76** [comment]
Works a treat, powered up and auto connected as expected, haven't seen any issues.

Just to mention something else, the "power" icon in the web interface of octoprint doesn't seem to update if the device powers off outside of pressing the actual button. If I refresh the page it will update. I have Domoticz power down my printer if it is idle for an amount of time. Does the plugin prob Domoticz for status changes, and if so can it push the web interface to update?
