### ISSUE TITLE
Invalid ip or unknown error connecting to 192....

### ISSUE THREAD

**Issue by kylana1** [jneilliii/OctoPrint-Domoticz#17]
Hello

my domoticz server not detected

[2020-04-21 22:34:41,377] ERROR: Invalid ip or unknown error connecting to 192.168.1.32:8181.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_domoticz/__init__.py", line 165, in check_status
    chk = response["result"][0]["Status"]
KeyError: 'result'

I try with full new installation and with local domoticz (127.0.0.1) so it's same issue

thanks in adavance

**Comment by jneilliii** [comment]
If you're getting a key error there in that bit of code then you are not getting an understandable response from the server. That could be that your id is incorrect possibly or you haven't include the login parameters maybe?

**Comment by kylana1** [comment]
hello thanks for quick answer.
I don't use password on local network.
but, I tested with new user create for octoprint 
https://drive.google.com/open?id=1pjvfTUAkjCyK0qYBoe8ets1AhWf25AJO
https://drive.google.com/open?id=1_z6S3wwtBc1UGkCApvYrcEDS1oacn0fF

**Comment by jneilliii** [comment]
I think that might be the issue on your domoticz side the device needs to be of type `Light/Switch` and subtype `Switch` to function properly.

**Comment by kylana1** [comment]
Thanks it's done
