### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by mattx38** [jneilliii/OctoPrint-Domoticz#19]
Hello,

Cannot manage to connect OctoPrint with my Domoticz server.

My Domoticz private IP is http://192.168.0.100:8080, but it keep saying me that Domoticz status is unknown and thaht I have to double check its IP/hostname.

I have no password to connect to Domoticz.
What should I check ? On Domoticz or OctoPrint

**Comment by yellowpanther** [comment]
Hello @mattx38,

Are you using python2 or python3 ?

Check the log file : ~/.octoprint/logs/plugin_domoticz_debug.log
If there is nothing in the file, check "Enable debug logging." in octoprint's domoticz plugin settings, restart octoprint and check the log file.

**Comment by jneilliii** [comment]
Thanks @yellowpanther for the assist. You may have to restart OctoPrint after enabling the debug logging for everything to initialize properly.

**Comment by mattx38** [comment]
Hello, 

My Python version is 2.7.16

Matt

**Comment by mattx38** [comment]
I did add the following line in confit.js :
debugMode: true

But no logs in MagicMirror/modules/octomirror-module at all

Matt

**Comment by yellowpanther** [comment]
I think you got the wrong thread ;)
This is the plugin for domoticz.

**Comment by mattx38** [comment]
Hello,

My bad !
You can close this issue. 

Matt

**Comment by mattx38** [comment]
Sorry and thank you for all you did. 

Matt
