### ISSUE TITLE
How to add in domoticz

### ISSUE THREAD

**Issue by nielssteenvoorde** [jneilliii/OctoPrint-Domoticz#3]
What kind of sensor do i have to add in domoticz and how do i configure. The plug-in on printer is installed without any problems

**Comment by jneilliii** [comment]
In theory any "switch" device with on/off support will work, but I have only personally tested a sonoff device flashed with tasmota.

**Comment by jneilliii** [comment]
This plugin just allows the sending of on/off commands to Domoticz, no data is sent related to printing data or anything like that for print monitoring.
