### ISSUE TITLE
Power off with delay

### ISSUE THREAD

**Issue by TheLion** [jneilliii/OctoPrint-Domoticz#5]
When I set the GCODE off delay for 300 seconds, it switches my switch (in my case my printer itself) in Domoticz off with the GCODE "M81 192.168.1.120 277" in the "After print job completes" GCODE script in Octoprint after 300 seconds like it should, but it even is switches off when I start a new printjob within those 5 minutes. Any way to counter that?

**Comment by jneilliii** [comment]
Currently no. Looks like I haven't integrated that option like I have in one of my other power control plugins.  Let me see if I can find that from my other plugin and integrate those changes into this one.  The setting that it will use is the Warn While Printing option.  When that is enabled and the gcode command is sent it will check to see if the printer is in a printing state and if it is it will ignore the off command.

**Comment by TheLion** [comment]
That would be a great addition!!

**Comment by jneilliii** [comment]
I just pushed an update to a new branch that is under development.  If you don't mind testing by installing using the url below in plugin manager that would be great.  My initial tests seem to indicate it's working as expected.

https://github.com/jneilliii/OctoPrint-Domoticz/archive/0.0.3.zip

**Comment by TheLion** [comment]
I'll test it after the current print. Currently running a 24+ hour print ;-)

**Comment by TheLion** [comment]
Hi. Took some time to get back to you. Sorry about that. 

It does work though.

**Comment by jneilliii** [comment]
Released version 0.0.3 that should resolve this request.
